import type {
  Student, Instructor, Event, Session, AnalyticsData, QuizSession, AttendanceRecord
} from '@/types';

export const mockStudents: Student[] = [
  {
    id: 'stu_001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@iitb.ac.in',
    role: 'student',
    rollNo: '23B030012',
    department: 'Computer Science & Engineering',
    year: 2,
    programme: 'BTech',
    attendancePercentage: 87,
    workshopsAttended: 5,
    enrolledCourses: ['course_001'],
    upcomingEvents: ['evt_001', 'evt_003'],
    modules: [
      {
        id: 'mod_001', title: 'Introduction to Mindfulness', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 88, maxMarks: 100,
        completedDate: '2024-02-10', duration: 60,
      },
      {
        id: 'mod_002', title: 'Stress Management Techniques', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 92, maxMarks: 100,
        completedDate: '2024-02-17', duration: 90,
      },
      {
        id: 'mod_003', title: 'Emotional Regulation & Resilience', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 79, maxMarks: 100,
        completedDate: '2024-02-24', duration: 75,
      },
      {
        id: 'mod_004', title: 'Positive Psychology Foundations', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 85, maxMarks: 100,
        completedDate: '2024-03-02', duration: 60,
      },
      {
        id: 'mod_005', title: 'Building Meaningful Relationships', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'pending',
        scheduledDate: '2024-03-16', scheduledTime: '14:00', venue: 'LC 101', duration: 90,
      },
      {
        id: 'mod_006', title: 'Academic Excellence & Wellbeing', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'pending',
        scheduledDate: '2024-03-23', scheduledTime: '10:00', venue: 'Seminar Hall 2', duration: 60,
      },
      {
        id: 'mod_007', title: 'Future Self Visualization', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'pending',
        scheduledDate: '2024-03-30', scheduledTime: '15:00', venue: 'Online (Meet)', duration: 75,
      },
    ],
  },
  {
    id: 'stu_002',
    name: 'Priya Patel',
    email: 'priya.patel@iitb.ac.in',
    role: 'student',
    rollNo: '22M10021',
    department: 'Electrical Engineering',
    year: 1,
    programme: 'MTech',
    attendancePercentage: 95,
    workshopsAttended: 7,
    enrolledCourses: ['course_001'],
    upcomingEvents: ['evt_002'],
    modules: [
      {
        id: 'mod_001', title: 'Introduction to Mindfulness', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 95, maxMarks: 100,
        completedDate: '2024-02-10', duration: 60,
      },
      {
        id: 'mod_002', title: 'Stress Management Techniques', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 88, maxMarks: 100,
        completedDate: '2024-02-17', duration: 90,
      },
    ],
  },
  {
    id: 'stu_003',
    name: 'Rohit Kumar',
    email: 'rohit.kumar@iitb.ac.in',
    role: 'student',
    rollNo: '21D02003',
    department: 'Mechanical Engineering',
    year: 3,
    programme: 'PhD',
    attendancePercentage: 72,
    workshopsAttended: 3,
    enrolledCourses: ['course_001'],
    upcomingEvents: ['evt_001', 'evt_002', 'evt_003'],
    modules: [
      {
        id: 'mod_001', title: 'Introduction to Mindfulness', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 78, maxMarks: 100,
        completedDate: '2024-02-10', duration: 60,
      },
    ],
  },
  {
    id: 'stu_004',
    name: 'Kavya Menon',
    email: 'kavya.menon@iitb.ac.in',
    role: 'student',
    rollNo: '23B040045',
    department: 'Civil Engineering',
    year: 1,
    programme: 'BTech',
    attendancePercentage: 100,
    workshopsAttended: 8,
    enrolledCourses: ['course_001'],
    upcomingEvents: ['evt_002'],
    modules: [
      {
        id: 'mod_001', title: 'Introduction to Mindfulness', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 98, maxMarks: 100,
        completedDate: '2024-02-10', duration: 60,
      },
      {
        id: 'mod_002', title: 'Stress Management Techniques', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 96, maxMarks: 100,
        completedDate: '2024-02-17', duration: 90,
      },
      {
        id: 'mod_003', title: 'Emotional Regulation & Resilience', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 91, maxMarks: 100,
        completedDate: '2024-02-24', duration: 75,
      },
    ],
  },
  {
    id: 'stu_005',
    name: 'Aditya Verma',
    email: 'aditya.verma@iitb.ac.in',
    role: 'student',
    rollNo: '22M21011',
    department: 'Chemical Engineering',
    year: 2,
    programme: 'MSc',
    attendancePercentage: 83,
    workshopsAttended: 4,
    enrolledCourses: ['course_001'],
    upcomingEvents: ['evt_003'],
    modules: [
      {
        id: 'mod_001', title: 'Introduction to Mindfulness', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 82, maxMarks: 100,
        completedDate: '2024-02-10', duration: 60,
      },
      {
        id: 'mod_002', title: 'Stress Management Techniques', courseId: 'course_001',
        courseName: 'Flourishing at IIT Bombay', status: 'completed', marks: 75, maxMarks: 100,
        completedDate: '2024-02-17', duration: 90,
      },
    ],
  },
];

export const mockInstructors: Instructor[] = [
  {
    id: 'ins_001',
    name: 'Dr. Ananya Krishnan',
    email: 'instructor@iitb.ac.in',
    role: 'instructor',
    department: 'Student Wellness Center',
    specialization: 'Mindfulness & Cognitive Behavioral Therapy',
    totalStudents: 142,
    sessions: [
      {
        id: 'ses_001',
        title: 'Wellness Wednesday — Mindful Breathing',
        instructorId: 'ins_001',
        instructorName: 'Dr. Ananya Krishnan',
        date: '2024-03-13',
        time: '16:00',
        venue: 'LC 101, Main Building',
        meetLink: 'https://meet.google.com/abc-defg-hij',
        participantCount: 38,
        status: 'upcoming',
        type: 'workshop',
        registrants: ['stu_001', 'stu_002', 'stu_004'],
      },
      {
        id: 'ses_002',
        title: 'Flourishing Friday — Gratitude Circle',
        instructorId: 'ins_001',
        instructorName: 'Dr. Ananya Krishnan',
        date: '2024-03-15',
        time: '17:00',
        venue: 'Seminar Hall 2',
        meetLink: 'https://meet.google.com/klm-nopq-rst',
        participantCount: 52,
        status: 'upcoming',
        type: 'group-session',
        registrants: ['stu_001', 'stu_003', 'stu_005'],
      },
      {
        id: 'ses_003',
        title: 'Introduction to Mindfulness — Session 1',
        instructorId: 'ins_001',
        instructorName: 'Dr. Ananya Krishnan',
        date: '2024-02-10',
        time: '14:00',
        venue: 'LC 101',
        participantCount: 65,
        actualAttendees: 61,
        status: 'completed',
        type: 'workshop',
        registrants: [],
      },
      {
        id: 'ses_004',
        title: 'Stress Management Workshop',
        instructorId: 'ins_001',
        instructorName: 'Dr. Ananya Krishnan',
        date: '2024-02-17',
        time: '14:00',
        venue: 'Seminar Hall 1',
        participantCount: 58,
        actualAttendees: 54,
        status: 'completed',
        type: 'workshop',
        registrants: [],
      },
      {
        id: 'ses_005',
        title: 'Emotional Regulation Session',
        instructorId: 'ins_001',
        instructorName: 'Dr. Ananya Krishnan',
        date: '2024-02-24',
        time: '15:00',
        venue: 'Online',
        participantCount: 72,
        actualAttendees: 68,
        status: 'completed',
        type: 'group-session',
        registrants: [],
      },
    ],
  },
  {
    id: 'ins_002',
    name: 'Prof. Vikram Singh',
    email: 'vikram.instructor@iitb.ac.in',
    role: 'instructor',
    department: 'Student Wellness Center',
    specialization: 'Positive Psychology & Academic Excellence',
    totalStudents: 98,
    sessions: [],
  },
];

export const mockEvents: Event[] = [
  {
    id: 'evt_001',
    title: 'Wellness Wednesday',
    description: 'A mid-week wellness reset. Mindful breathing, guided meditation, and peer connections in a calm environment.',
    date: '2024-03-13',
    time: '16:00',
    venue: 'Lecture Complex 101',
    type: 'wellness',
    organizer: 'Dr. Ananya Krishnan',
    capacity: 60,
    registeredCount: 38,
    tags: ['mindfulness', 'meditation', 'wellness'],
    isRecurring: true,
    volunteerSlots: 5,
  },
  {
    id: 'evt_002',
    title: 'Flourishing Friday',
    description: 'End your week on a high note. Gratitude circles, positive sharing, and community bonding.',
    date: '2024-03-15',
    time: '17:00',
    venue: 'Seminar Hall 2',
    type: 'social',
    organizer: 'Dr. Ananya Krishnan',
    capacity: 80,
    registeredCount: 52,
    tags: ['gratitude', 'community', 'social'],
    isRecurring: true,
    volunteerSlots: 8,
  },
  {
    id: 'evt_003',
    title: 'Academic Stress Workshop',
    description: 'Learn practical tools for managing exam stress, time management, and maintaining work-life balance.',
    date: '2024-03-20',
    time: '14:00',
    venue: 'Kohinoor Hall',
    type: 'workshop',
    organizer: 'Prof. Vikram Singh',
    capacity: 100,
    registeredCount: 67,
    tags: ['academics', 'stress', 'time-management'],
    isRecurring: false,
    volunteerSlots: 10,
  },
  {
    id: 'evt_004',
    title: 'Mental Health Awareness Talk',
    description: 'Open conversation on mental health, destigmatization, and available resources at IIT Bombay.',
    date: '2024-03-25',
    time: '18:00',
    venue: 'Victor Menezes Convention Centre',
    type: 'seminar',
    organizer: 'Student Wellness Center',
    capacity: 200,
    registeredCount: 143,
    tags: ['mental-health', 'awareness', 'community'],
    isRecurring: false,
    volunteerSlots: 15,
  },
  {
    id: 'evt_005',
    title: 'Yoga & Movement Session',
    description: 'Gentle yoga and movement practices for stress relief and body awareness.',
    date: '2024-03-27',
    time: '07:00',
    venue: 'Student Activity Centre Lawn',
    type: 'wellness',
    organizer: 'Dr. Ananya Krishnan',
    capacity: 40,
    registeredCount: 22,
    tags: ['yoga', 'movement', 'morning'],
    isRecurring: true,
    volunteerSlots: 3,
  },
];

export const mockAnalytics: AnalyticsData = {
  totalStudents: 1284,
  totalWorkshops: 47,
  activeCourses: 6,
  engagementRate: 78,
  workshopsPerMonth: [
    { month: 'Aug', workshops: 3 },
    { month: 'Sep', workshops: 5 },
    { month: 'Oct', workshops: 7 },
    { month: 'Nov', workshops: 4 },
    { month: 'Dec', workshops: 2 },
    { month: 'Jan', workshops: 6 },
    { month: 'Feb', workshops: 9 },
    { month: 'Mar', workshops: 11 },
  ],
  engagementByDept: [
    { dept: 'CSE', students: 245, engagement: 82 },
    { dept: 'EE', students: 198, engagement: 75 },
    { dept: 'ME', students: 176, engagement: 68 },
    { dept: 'CE', students: 142, engagement: 79 },
    { dept: 'Chem', students: 115, engagement: 71 },
    { dept: 'Phy', students: 98, engagement: 85 },
    { dept: 'Math', students: 87, engagement: 77 },
    { dept: 'HS', students: 223, engagement: 91 },
  ],
  programmeDistribution: [
    { name: 'BTech', value: 58, color: '#6C63FF' },
    { name: 'MTech', value: 22, color: '#00C9A7' },
    { name: 'PhD', value: 13, color: '#F59E0B' },
    { name: 'MSc', value: 7, color: '#EF4444' },
  ],
  attendanceHeatmap: Array.from({ length: 7 }, (_, day) =>
    Array.from({ length: 12 }, (_, week) => ({
      date: `2024-W${week + 1}-${day + 1}`,
      count: Math.floor(Math.random() * 50),
    }))
  ),
};

export const mockQuizSessions: QuizSession[] = [
  {
    sessionId: 'ses_001',
    sessionTitle: 'Wellness Wednesday — Mindful Breathing',
    quizActive: false,
    feedbackActive: false,
    quizLink: 'https://forms.google.com/quiz001',
    feedbackLink: 'https://forms.google.com/feedback001',
  },
  {
    sessionId: 'ses_002',
    sessionTitle: 'Flourishing Friday — Gratitude Circle',
    quizActive: false,
    feedbackActive: false,
    quizLink: 'https://forms.google.com/quiz002',
    feedbackLink: 'https://forms.google.com/feedback002',
  },
  {
    sessionId: 'ses_003',
    sessionTitle: 'Introduction to Mindfulness — Session 1',
    quizActive: false,
    feedbackActive: false,
    quizLink: 'https://forms.google.com/quiz003',
    feedbackLink: 'https://forms.google.com/feedback003',
  },
];

export const mockAttendanceStudents: AttendanceRecord[] = mockStudents.map((s) => ({
  id: `att_${s.id}`,
  studentId: s.id,
  studentName: s.name,
  sessionId: 'ses_001',
  sessionTitle: 'Wellness Wednesday — Mindful Breathing',
  date: '2024-03-13',
  status: 'present' as const,
}));

export const recentActivity = [
  { id: 1, action: 'Arjun Sharma completed Module 4', time: '2 min ago', type: 'completion', icon: '✅' },
  { id: 2, action: 'New registration: Wellness Wednesday (38 students)', time: '15 min ago', type: 'registration', icon: '📋' },
  { id: 3, action: 'Dr. Krishnan uploaded Session 5 materials', time: '1 hr ago', type: 'upload', icon: '📁' },
  { id: 4, action: 'Quiz activated for Module 3 by Ms. Neha', time: '2 hrs ago', type: 'quiz', icon: '📝' },
  { id: 5, action: 'Kavya Menon scored 98/100 in Module 1 quiz', time: '3 hrs ago', type: 'score', icon: '🏆' },
  { id: 6, action: '15 new students enrolled in Course', time: '5 hrs ago', type: 'enrollment', icon: '👥' },
  { id: 7, action: 'Flourishing Friday event capacity reached 65%', time: '6 hrs ago', type: 'event', icon: '🎯' },
  { id: 8, action: 'Academic Stress Workshop — 67 registrations', time: 'Yesterday', type: 'registration', icon: '📋' },
];
